version: '3.9'

services:
  mongo_db:
    container_name: mongo_db
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    
  node:
    container_name: todo_test
    image: todo_test:1.1
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017/todo_express
    depends_on:
      - mongo_db

volumes:
  mongo-db: